begin;

-- Base tables that predate the incremental migrations in this repository.
-- Run this file first for a new Supabase project.

create table if not exists public.raw_records (
    id bigint generated by default as identity primary key,
    source text not null,
    record_type text not null,
    source_record_id text not null,
    measured_at timestamptz,
    payload jsonb not null,
    fetched_at timestamptz not null default now(),
    unique (source, record_type, source_record_id)
);

create index if not exists raw_records_lookup_idx
    on public.raw_records (source, record_type, fetched_at desc);

create table if not exists public.health_records (
    id bigint generated by default as identity primary key,
    source text not null,
    key text not null,
    source_record_id text not null,
    measured_at timestamptz not null,
    source_updated_at timestamptz,
    sid text,
    zone_name text,
    zone_offset integer,
    value jsonb,
    metrics jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, key, source_record_id)
);

create index if not exists health_records_key_measured_idx
    on public.health_records (source, key, measured_at desc);

create table if not exists public.heart_rate_samples (
    id bigint generated by default as identity primary key,
    source text not null,
    measured_at timestamptz not null,
    bpm integer not null check (bpm > 0),
    source_record_id text,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (source, measured_at)
);

create index if not exists heart_rate_samples_measured_idx
    on public.heart_rate_samples (source, measured_at desc);

create table if not exists public.spo2_samples (
    id bigint generated by default as identity primary key,
    source text not null,
    measured_at timestamptz not null,
    percent numeric(5, 2) not null check (percent between 0 and 100),
    source_record_id text,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (source, measured_at)
);

create index if not exists spo2_samples_measured_idx
    on public.spo2_samples (source, measured_at desc);

create table if not exists public.intensity_samples (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    measured_at timestamptz not null,
    zone_name text,
    zone_offset integer,
    source_updated_at timestamptz,
    raw_record_id bigint,
    created_at timestamptz not null default now(),
    unique (source, source_record_id, measured_at)
);

create index if not exists intensity_samples_measured_idx
    on public.intensity_samples (source, measured_at desc);

create table if not exists public.body_measurements (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    measured_at timestamptz not null,
    weight_kg numeric,
    bmi numeric,
    body_fat_pct numeric,
    muscle_mass_kg numeric,
    bone_mass_kg numeric,
    body_water_pct numeric,
    basal_metabolism_kcal numeric,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists body_measurements_measured_idx
    on public.body_measurements (source, measured_at desc);

create table if not exists public.menstrual_records (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    record_type text not null check (
        record_type in ('period_start', 'period_end')
    ),
    start_at timestamptz not null,
    end_at timestamptz,
    value jsonb,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists menstrual_records_start_idx
    on public.menstrual_records (source, start_at desc);

create table if not exists public.sleep_sessions (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    start_at timestamptz not null,
    end_at timestamptz not null,
    score numeric,
    avg_hr numeric,
    avg_spo2 numeric,
    avg_hrv_ms numeric,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists sleep_sessions_start_idx
    on public.sleep_sessions (source, start_at desc);

create table if not exists public.sleep_stages (
    id bigint generated by default as identity primary key,
    sleep_session_id bigint not null
        references public.sleep_sessions(id) on delete cascade,
    stage text not null,
    start_at timestamptz not null,
    end_at timestamptz not null,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists sleep_stages_session_start_idx
    on public.sleep_stages (sleep_session_id, start_at);

create table if not exists public.workouts (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    activity_type text,
    start_at timestamptz not null,
    end_at timestamptz not null,
    duration_s numeric,
    distance_m numeric,
    calories_kcal numeric,
    avg_hr numeric,
    max_hr numeric,
    min_hr numeric,
    steps numeric,
    vo2_max numeric,
    training_load numeric,
    recovery_min numeric,
    route jsonb,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists workouts_start_idx
    on public.workouts (source, start_at desc);

create table if not exists public.xiaomi_sync_state (
    source text not null,
    key text not null,
    discovered boolean not null default false,
    initial_backfill_complete boolean not null default false,
    next_start_time bigint,
    source_checked_at timestamptz,
    source_check_status text,
    source_latest_at timestamptz,
    next_recheck_at timestamptz,
    empty_check_count integer not null default 0 check (empty_check_count >= 0),
    source_check_detail jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (source, key)
);

create table if not exists public.xiaomi_sync_jobs (
    job_id text primary key,
    metric text,
    status text not null check (
        status in ('queued', 'running', 'completed', 'failed')
    ),
    created_at timestamptz not null,
    started_at timestamptz,
    completed_at timestamptz,
    result jsonb,
    error text
);

create index if not exists xiaomi_sync_jobs_metric_completed_idx
    on public.xiaomi_sync_jobs (metric, completed_at desc);

alter table public.raw_records enable row level security;
alter table public.health_records enable row level security;
alter table public.heart_rate_samples enable row level security;
alter table public.spo2_samples enable row level security;
alter table public.intensity_samples enable row level security;
alter table public.body_measurements enable row level security;
alter table public.menstrual_records enable row level security;
alter table public.sleep_sessions enable row level security;
alter table public.sleep_stages enable row level security;
alter table public.workouts enable row level security;
alter table public.xiaomi_sync_state enable row level security;
alter table public.xiaomi_sync_jobs enable row level security;

revoke all on table public.raw_records from anon, authenticated;
revoke all on table public.health_records from anon, authenticated;
revoke all on table public.heart_rate_samples from anon, authenticated;
revoke all on table public.spo2_samples from anon, authenticated;
revoke all on table public.intensity_samples from anon, authenticated;
revoke all on table public.body_measurements from anon, authenticated;
revoke all on table public.menstrual_records from anon, authenticated;
revoke all on table public.sleep_sessions from anon, authenticated;
revoke all on table public.sleep_stages from anon, authenticated;
revoke all on table public.workouts from anon, authenticated;
revoke all on table public.xiaomi_sync_state from anon, authenticated;
revoke all on table public.xiaomi_sync_jobs from anon, authenticated;

grant select, insert, update, delete on table public.raw_records to service_role;
grant select, insert, update, delete on table public.health_records to service_role;
grant select, insert, update, delete on table public.heart_rate_samples to service_role;
grant select, insert, update, delete on table public.spo2_samples to service_role;
grant select, insert, update, delete on table public.intensity_samples to service_role;
grant select, insert, update, delete on table public.body_measurements to service_role;
grant select, insert, update, delete on table public.menstrual_records to service_role;
grant select, insert, update, delete on table public.sleep_sessions to service_role;
grant select, insert, update, delete on table public.sleep_stages to service_role;
grant select, insert, update, delete on table public.workouts to service_role;
grant select, insert, update, delete on table public.xiaomi_sync_state to service_role;
grant select, insert, update, delete on table public.xiaomi_sync_jobs to service_role;

revoke all on sequence public.raw_records_id_seq from anon, authenticated;
revoke all on sequence public.health_records_id_seq from anon, authenticated;
revoke all on sequence public.heart_rate_samples_id_seq from anon, authenticated;
revoke all on sequence public.spo2_samples_id_seq from anon, authenticated;
revoke all on sequence public.intensity_samples_id_seq from anon, authenticated;
revoke all on sequence public.body_measurements_id_seq from anon, authenticated;
revoke all on sequence public.menstrual_records_id_seq from anon, authenticated;
revoke all on sequence public.sleep_sessions_id_seq from anon, authenticated;
revoke all on sequence public.sleep_stages_id_seq from anon, authenticated;
revoke all on sequence public.workouts_id_seq from anon, authenticated;

grant usage, select on sequence public.raw_records_id_seq to service_role;
grant usage, select on sequence public.health_records_id_seq to service_role;
grant usage, select on sequence public.heart_rate_samples_id_seq to service_role;
grant usage, select on sequence public.spo2_samples_id_seq to service_role;
grant usage, select on sequence public.intensity_samples_id_seq to service_role;
grant usage, select on sequence public.body_measurements_id_seq to service_role;
grant usage, select on sequence public.menstrual_records_id_seq to service_role;
grant usage, select on sequence public.sleep_sessions_id_seq to service_role;
grant usage, select on sequence public.sleep_stages_id_seq to service_role;
grant usage, select on sequence public.workouts_id_seq to service_role;

commit;
