begin;

-- Base tables that predate the incremental migrations in this repository.
-- Run this file first for a new Supabase project.

create table if not exists public.raw_records (
    id bigint generated by default as identity primary key,
    source text not null,
    record_type text not null,
    source_record_id text not null,
    measured_at timestamptz,
    payload jsonb not null,
    fetched_at timestamptz not null default now(),
    unique (source, record_type, source_record_id)
);

create index if not exists raw_records_lookup_idx
    on public.raw_records (source, record_type, fetched_at desc);

create table if not exists public.health_records (
    id bigint generated by default as identity primary key,
    source text not null,
    key text not null,
    source_record_id text not null,
    measured_at timestamptz not null,
    source_updated_at timestamptz,
    sid text,
    zone_name text,
    zone_offset integer,
    value jsonb,
    metrics jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, key, source_record_id)
);

create index if not exists health_records_key_measured_idx
    on public.health_records (source, key, measured_at desc);

create table if not exists public.heart_rate_samples (
    id bigint generated by default as identity primary key,
    source text not null,
    measured_at timestamptz not null,
    bpm integer not null check (bpm > 0),
    source_record_id text,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (source, measured_at)
);

create index if not exists heart_rate_samples_measured_idx
    on public.heart_rate_samples (source, measured_at desc);

create table if not exists public.spo2_samples (
    id bigint generated by default as identity primary key,
    source text not null,
    measured_at timestamptz not null,
    percent numeric(5, 2) not null check (percent between 0 and 100),
    source_record_id text,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (source, measured_at)
);

create index if not exists spo2_samples_measured_idx
    on public.spo2_samples (source, measured_at desc);

create table if not exists public.intensity_samples (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    measured_at timestamptz not null,
    zone_name text,
    zone_offset integer,
    source_updated_at timestamptz,
    raw_record_id bigint,
    created_at timestamptz not null default now(),
    unique (source, source_record_id, measured_at)
);

create index if not exists intensity_samples_measured_idx
    on public.intensity_samples (source, measured_at desc);

create table if not exists public.body_measurements (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    measured_at timestamptz not null,
    weight_kg numeric,
    bmi numeric,
    body_fat_pct numeric,
    muscle_mass_kg numeric,
    bone_mass_kg numeric,
    body_water_pct numeric,
    basal_metabolism_kcal numeric,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists body_measurements_measured_idx
    on public.body_measurements (source, measured_at desc);

create table if not exists public.menstrual_records (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    record_type text not null check (
        record_type in ('period_start', 'period_end')
    ),
    start_at timestamptz not null,
    end_at timestamptz,
    value jsonb,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists menstrual_records_start_idx
    on public.menstrual_records (source, start_at desc);

create table if not exists public.sleep_sessions (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    start_at timestamptz not null,
    end_at timestamptz not null,
    score numeric,
    avg_hr numeric,
    avg_spo2 numeric,
    avg_hrv_ms numeric,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists sleep_sessions_start_idx
    on public.sleep_sessions (source, start_at desc);

create table if not exists public.sleep_stages (
    id bigint generated by default as identity primary key,
    sleep_session_id bigint not null
        references public.sleep_sessions(id) on delete cascade,
    stage text not null,
    start_at timestamptz not null,
    end_at timestamptz not null,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists sleep_stages_session_start_idx
    on public.sleep_stages (sleep_session_id, start_at);

create table if not exists public.workouts (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    activity_type text,
    start_at timestamptz not null,
    end_at timestamptz not null,
    duration_s numeric,
    distance_m numeric,
    calories_kcal numeric,
    avg_hr numeric,
    max_hr numeric,
    min_hr numeric,
    steps numeric,
    vo2_max numeric,
    training_load numeric,
    recovery_min numeric,
    route jsonb,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists workouts_start_idx
    on public.workouts (source, start_at desc);

create table if not exists public.xiaomi_sync_state (
    source text not null,
    key text not null,
    discovered boolean not null default false,
    initial_backfill_complete boolean not null default false,
    next_start_time bigint,
    source_checked_at timestamptz,
    source_check_status text,
    source_latest_at timestamptz,
    next_recheck_at timestamptz,
    empty_check_count integer not null default 0 check (empty_check_count >= 0),
    source_check_detail jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (source, key)
);

create table if not exists public.xiaomi_sync_jobs (
    job_id text primary key,
    metric text,
    status text not null check (
        status in ('queued', 'running', 'completed', 'failed')
    ),
    created_at timestamptz not null,
    started_at timestamptz,
    completed_at timestamptz,
    result jsonb,
    error text
);

create index if not exists xiaomi_sync_jobs_metric_completed_idx
    on public.xiaomi_sync_jobs (metric, completed_at desc);

alter table public.raw_records enable row level security;
alter table public.health_records enable row level security;
alter table public.heart_rate_samples enable row level security;
alter table public.spo2_samples enable row level security;
alter table public.intensity_samples enable row level security;
alter table public.body_measurements enable row level security;
alter table public.menstrual_records enable row level security;
alter table public.sleep_sessions enable row level security;
alter table public.sleep_stages enable row level security;
alter table public.workouts enable row level security;
alter table public.xiaomi_sync_state enable row level security;
alter table public.xiaomi_sync_jobs enable row level security;

revoke all on table public.raw_records from anon, authenticated;
revoke all on table public.health_records from anon, authenticated;
revoke all on table public.heart_rate_samples from anon, authenticated;
revoke all on table public.spo2_samples from anon, authenticated;
revoke all on table public.intensity_samples from anon, authenticated;
revoke all on table public.body_measurements from anon, authenticated;
revoke all on table public.menstrual_records from anon, authenticated;
revoke all on table public.sleep_sessions from anon, authenticated;
revoke all on table public.sleep_stages from anon, authenticated;
revoke all on table public.workouts from anon, authenticated;
revoke all on table public.xiaomi_sync_state from anon, authenticated;
revoke all on table public.xiaomi_sync_jobs from anon, authenticated;

grant select, insert, update, delete on table public.raw_records to service_role;
grant select, insert, update, delete on table public.health_records to service_role;
grant select, insert, update, delete on table public.heart_rate_samples to service_role;
grant select, insert, update, delete on table public.spo2_samples to service_role;
grant select, insert, update, delete on table public.intensity_samples to service_role;
grant select, insert, update, delete on table public.body_measurements to service_role;
grant select, insert, update, delete on table public.menstrual_records to service_role;
grant select, insert, update, delete on table public.sleep_sessions to service_role;
grant select, insert, update, delete on table public.sleep_stages to service_role;
grant select, insert, update, delete on table public.workouts to service_role;
grant select, insert, update, delete on table public.xiaomi_sync_state to service_role;
grant select, insert, update, delete on table public.xiaomi_sync_jobs to service_role;

revoke all on sequence public.raw_records_id_seq from anon, authenticated;
revoke all on sequence public.health_records_id_seq from anon, authenticated;
revoke all on sequence public.heart_rate_samples_id_seq from anon, authenticated;
revoke all on sequence public.spo2_samples_id_seq from anon, authenticated;
revoke all on sequence public.intensity_samples_id_seq from anon, authenticated;
revoke all on sequence public.body_measurements_id_seq from anon, authenticated;
revoke all on sequence public.menstrual_records_id_seq from anon, authenticated;
revoke all on sequence public.sleep_sessions_id_seq from anon, authenticated;
revoke all on sequence public.sleep_stages_id_seq from anon, authenticated;
revoke all on sequence public.workouts_id_seq from anon, authenticated;

grant usage, select on sequence public.raw_records_id_seq to service_role;
grant usage, select on sequence public.health_records_id_seq to service_role;
grant usage, select on sequence public.heart_rate_samples_id_seq to service_role;
grant usage, select on sequence public.spo2_samples_id_seq to service_role;
grant usage, select on sequence public.intensity_samples_id_seq to service_role;
grant usage, select on sequence public.body_measurements_id_seq to service_role;
grant usage, select on sequence public.menstrual_records_id_seq to service_role;
grant usage, select on sequence public.sleep_sessions_id_seq to service_role;
grant usage, select on sequence public.sleep_stages_id_seq to service_role;
grant usage, select on sequence public.workouts_id_seq to service_role;


create table if not exists public.glucose_samples (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    measured_at timestamptz not null,
    glucose_mg_dl integer not null check (glucose_mg_dl > 0),
    glucose_mmol_l numeric(6,2) not null check (glucose_mmol_l > 0),
    direction text,
    created_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists glucose_samples_source_measured_at_idx
    on public.glucose_samples (source, measured_at desc);

alter table public.glucose_samples enable row level security;

create table if not exists public.xiaomi_coverage_ranges (
    source text not null default 'xiaomi',
    key text not null,
    range_start timestamptz not null,
    range_end timestamptz not null,
    checked_at timestamptz not null default now(),
    status text not null check (status in ('success', 'failed')),
    primary key (source, key, range_start, range_end),
    check (range_end >= range_start)
);

create index if not exists xiaomi_coverage_ranges_lookup_idx
    on public.xiaomi_coverage_ranges (source, key, range_start, range_end);

-- Normalized Xiaomi Health diet records.
-- The production database may already contain these tables from the initial
-- read-only probe migration; every statement is idempotent for that case.

create table if not exists public.diet_meals (
    id bigint generated by default as identity primary key,
    source text not null default 'xiaomi',
    source_meal_id text not null,
    meal_date date not null,
    dining smallint not null,
    meal_type text not null check (
        meal_type in (
            'breakfast',
            'morning_snack',
            'lunch',
            'afternoon_snack',
            'dinner',
            'evening_snack',
            'other'
        )
    ),
    recorded_at timestamptz,
    total_calorie_kcal numeric,
    total_protein_g numeric,
    total_carbohydrate_g numeric,
    total_fat_g numeric,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_meal_id)
);

create table if not exists public.diet_food_items (
    id bigint generated by default as identity primary key,
    diet_meal_id bigint not null references public.diet_meals(id) on delete cascade,
    source text not null default 'xiaomi',
    source_item_id text not null,
    item_index integer not null check (item_index >= 0),
    food_id text,
    name text,
    quantity numeric,
    unit text,
    calorie_kcal numeric,
    protein_g numeric,
    carbohydrate_g numeric,
    fat_g numeric,
    dietary_fiber_g numeric,
    minerals numeric,
    vitamins numeric,
    health_light smallint,
    image_url text,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_item_id, item_index)
);

create index if not exists diet_meals_recorded_at_idx
    on public.diet_meals (recorded_at);
create index if not exists diet_meals_meal_date_idx
    on public.diet_meals (meal_date);
create index if not exists diet_food_items_meal_idx
    on public.diet_food_items (diet_meal_id);

alter table public.diet_meals enable row level security;
alter table public.diet_food_items enable row level security;

-- Align normalized Xiaomi diet meal types with the six dining codes used by the app.

alter table public.diet_meals
    drop constraint if exists diet_meals_meal_type_check;

alter table public.diet_meals
    add constraint diet_meals_meal_type_check
    check (
        meal_type in (
            'breakfast',
            'morning_snack',
            'lunch',
            'afternoon_snack',
            'dinner',
            'evening_snack',
            'other'
        )
    );

update public.diet_meals
set meal_type = case dining
    when 1 then 'breakfast'
    when 2 then 'morning_snack'
    when 3 then 'lunch'
    when 4 then 'afternoon_snack'
    when 5 then 'dinner'
    when 6 then 'evening_snack'
    else 'other'
end,
updated_at = now();

create table if not exists public.device_presence (
    id bigint generated by default as identity primary key,
    observed_at timestamptz not null,
    device text not null default 'primary_phone',
    event text not null check (event = 'unlock'),
    latitude numeric(6, 3) not null check (latitude between -90 and 90),
    longitude numeric(7, 3) not null check (longitude between -180 and 180),
    accuracy numeric(10, 2) check (accuracy is null or accuracy >= 0),
    city text,
    region text,
    country text,
    source text not null default 'automate_location'
        check (source = 'automate_location'),
    created_at timestamptz not null default now()
);

create index if not exists device_presence_device_observed_idx
    on public.device_presence (device, observed_at desc);

create table if not exists public.wake_report_deliveries (
    id uuid primary key,
    report_date date not null,
    device text not null default 'primary_phone',
    sleep_source_record_id text not null,
    sleep_fingerprint text not null,
    report_kind text not null check (
        report_kind in ('morning', 'sleep_update', 'new_sleep')
    ),
    includes_yesterday_health boolean not null default false,
    sleep_snapshot jsonb not null,
    presence_id bigint references public.device_presence(id) on delete set null,
    status text not null check (status in ('triggering', 'completed')),
    claimed_at timestamptz not null,
    triggered_at timestamptz,
    created_at timestamptz not null default now(),
    unique (device, sleep_fingerprint)
);

create index if not exists wake_report_deliveries_day_idx
    on public.wake_report_deliveries (device, report_date, created_at);

create index if not exists wake_report_deliveries_presence_idx
    on public.wake_report_deliveries (presence_id);

alter table public.device_presence enable row level security;
alter table public.wake_report_deliveries enable row level security;

revoke all on table public.device_presence from anon, authenticated;
revoke all on table public.wake_report_deliveries from anon, authenticated;
revoke all on sequence public.device_presence_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.device_presence to service_role;
grant select, insert, update, delete on table public.wake_report_deliveries to service_role;
grant usage, select on sequence public.device_presence_id_seq to service_role;


-- Split location updates from unlock probes and deduplicate by stable sleep id.

alter table public.device_presence
    drop constraint if exists device_presence_event_check;

alter table public.device_presence
    add constraint device_presence_event_check
    check (event in ('unlock', 'location_update'));

create table if not exists public.device_wake_state (
    device text primary key,
    last_unlock_at timestamptz not null,
    source text not null default 'automate_unlock'
        check (source = 'automate_unlock'),
    updated_at timestamptz not null default now()
);

alter table public.device_wake_state enable row level security;
revoke all on table public.device_wake_state from anon, authenticated;
grant select, insert, update, delete on table public.device_wake_state to service_role;

create or replace function public.keep_latest_device_unlock()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.last_unlock_at := greatest(old.last_unlock_at, new.last_unlock_at);
    new.updated_at := now();
    return new;
end;
$$;

revoke all on function public.keep_latest_device_unlock() from public;

drop trigger if exists device_wake_state_keep_latest on public.device_wake_state;
create trigger device_wake_state_keep_latest
before update on public.device_wake_state
for each row execute function public.keep_latest_device_unlock();

alter table public.wake_report_deliveries
    drop constraint if exists wake_report_deliveries_report_kind_check;

alter table public.wake_report_deliveries
    add constraint wake_report_deliveries_report_kind_check
    check (report_kind in ('morning', 'nap', 'sleep_update', 'new_sleep'));

with ranked_deliveries as (
    select id, row_number() over (
        partition by device, sleep_source_record_id
        order by
            (status = 'completed') desc,
            coalesce(triggered_at, claimed_at, created_at) desc,
            id desc
    ) as row_number
    from public.wake_report_deliveries
)
delete from public.wake_report_deliveries as delivery
using ranked_deliveries as ranked
where delivery.id = ranked.id
  and ranked.row_number > 1;

alter table public.wake_report_deliveries
    drop constraint if exists wake_report_deliveries_device_sleep_fingerprint_key;

alter table public.wake_report_deliveries
    add constraint wake_report_deliveries_device_sleep_source_record_id_key
    unique (device, sleep_source_record_id);


create table if not exists public.morning_context_snapshots (
    report_id uuid primary key
        references public.wake_report_deliveries(id) on delete cascade,
    schema_version text not null,
    source_versions jsonb not null default '{}'::jsonb,
    payload jsonb not null,
    snapshot_mode text not null check (
        snapshot_mode in ('native', 'legacy_hydrated')
    ),
    generated_at timestamptz not null default now()
);

alter table public.morning_context_snapshots enable row level security;

revoke all on table public.morning_context_snapshots
    from anon, authenticated, service_role;

grant select, insert on table public.morning_context_snapshots to service_role;

create or replace function public.get_morning_heart_rate_daily(
    p_start_at timestamptz,
    p_end_at timestamptz,
    p_timezone text
)
returns table (
    day date,
    sample_count bigint,
    avg_bpm double precision,
    min_bpm integer,
    max_bpm integer
)
language sql
stable
security invoker
set search_path = ''
as $$
    select
        (samples.measured_at at time zone p_timezone)::date as day,
        count(*) as sample_count,
        avg(samples.bpm)::double precision as avg_bpm,
        min(samples.bpm)::integer as min_bpm,
        max(samples.bpm)::integer as max_bpm
    from public.heart_rate_samples as samples
    where samples.source = 'xiaomi'
      and samples.measured_at >= p_start_at
      and samples.measured_at <= p_end_at
    group by (samples.measured_at at time zone p_timezone)::date
    order by day;
$$;

revoke all on function public.get_morning_heart_rate_daily(
    timestamptz, timestamptz, text
) from public, anon, authenticated;

grant execute on function public.get_morning_heart_rate_daily(
    timestamptz, timestamptz, text
) to service_role;

revoke all on table public.morning_context_snapshots from service_role;

grant select, insert on table public.morning_context_snapshots to service_role;


alter table public.device_presence
    add column if not exists district text;



-- Keep all health and report tables private to the server-side service role.

alter table public.raw_records enable row level security;
alter table public.health_records enable row level security;
alter table public.heart_rate_samples enable row level security;
alter table public.spo2_samples enable row level security;
alter table public.intensity_samples enable row level security;
alter table public.body_measurements enable row level security;
alter table public.menstrual_records enable row level security;
alter table public.sleep_sessions enable row level security;
alter table public.sleep_stages enable row level security;
alter table public.workouts enable row level security;
alter table public.xiaomi_sync_state enable row level security;
alter table public.xiaomi_sync_jobs enable row level security;
alter table public.glucose_samples enable row level security;
alter table public.xiaomi_coverage_ranges enable row level security;
alter table public.diet_meals enable row level security;
alter table public.diet_food_items enable row level security;
alter table public.device_presence enable row level security;
alter table public.wake_report_deliveries enable row level security;
alter table public.device_wake_state enable row level security;
alter table public.morning_context_snapshots enable row level security;

revoke all on table public.raw_records from anon, authenticated;
revoke all on table public.health_records from anon, authenticated;
revoke all on table public.heart_rate_samples from anon, authenticated;
revoke all on table public.spo2_samples from anon, authenticated;
revoke all on table public.intensity_samples from anon, authenticated;
revoke all on table public.body_measurements from anon, authenticated;
revoke all on table public.menstrual_records from anon, authenticated;
revoke all on table public.sleep_sessions from anon, authenticated;
revoke all on table public.sleep_stages from anon, authenticated;
revoke all on table public.workouts from anon, authenticated;
revoke all on table public.xiaomi_sync_state from anon, authenticated;
revoke all on table public.xiaomi_sync_jobs from anon, authenticated;
revoke all on table public.glucose_samples from anon, authenticated;
revoke all on table public.xiaomi_coverage_ranges from anon, authenticated;
revoke all on table public.diet_meals from anon, authenticated;
revoke all on table public.diet_food_items from anon, authenticated;
revoke all on table public.device_presence from anon, authenticated;
revoke all on table public.wake_report_deliveries from anon, authenticated;
revoke all on table public.device_wake_state from anon, authenticated;
revoke all on table public.morning_context_snapshots from anon, authenticated;

grant select, insert, update, delete on table public.raw_records to service_role;
grant select, insert, update, delete on table public.health_records to service_role;
grant select, insert, update, delete on table public.heart_rate_samples to service_role;
grant select, insert, update, delete on table public.spo2_samples to service_role;
grant select, insert, update, delete on table public.intensity_samples to service_role;
grant select, insert, update, delete on table public.body_measurements to service_role;
grant select, insert, update, delete on table public.menstrual_records to service_role;
grant select, insert, update, delete on table public.sleep_sessions to service_role;
grant select, insert, update, delete on table public.sleep_stages to service_role;
grant select, insert, update, delete on table public.workouts to service_role;
grant select, insert, update, delete on table public.xiaomi_sync_state to service_role;
grant select, insert, update, delete on table public.xiaomi_sync_jobs to service_role;
grant select, insert, update, delete on table public.glucose_samples to service_role;
grant select, insert, update, delete on table public.xiaomi_coverage_ranges to service_role;
grant select, insert, update, delete on table public.diet_meals to service_role;
grant select, insert, update, delete on table public.diet_food_items to service_role;
grant select, insert, update, delete on table public.device_presence to service_role;
grant select, insert, update, delete on table public.wake_report_deliveries to service_role;
grant select, insert, update, delete on table public.device_wake_state to service_role;

revoke all on table public.morning_context_snapshots from service_role;
grant select, insert on table public.morning_context_snapshots to service_role;

revoke all on sequence public.raw_records_id_seq from anon, authenticated;
revoke all on sequence public.health_records_id_seq from anon, authenticated;
revoke all on sequence public.heart_rate_samples_id_seq from anon, authenticated;
revoke all on sequence public.spo2_samples_id_seq from anon, authenticated;
revoke all on sequence public.intensity_samples_id_seq from anon, authenticated;
revoke all on sequence public.body_measurements_id_seq from anon, authenticated;
revoke all on sequence public.menstrual_records_id_seq from anon, authenticated;
revoke all on sequence public.sleep_sessions_id_seq from anon, authenticated;
revoke all on sequence public.sleep_stages_id_seq from anon, authenticated;
revoke all on sequence public.workouts_id_seq from anon, authenticated;
revoke all on sequence public.glucose_samples_id_seq from anon, authenticated;
revoke all on sequence public.diet_meals_id_seq from anon, authenticated;
revoke all on sequence public.diet_food_items_id_seq from anon, authenticated;
revoke all on sequence public.device_presence_id_seq from anon, authenticated;

grant usage, select on sequence public.raw_records_id_seq to service_role;
grant usage, select on sequence public.health_records_id_seq to service_role;
grant usage, select on sequence public.heart_rate_samples_id_seq to service_role;
grant usage, select on sequence public.spo2_samples_id_seq to service_role;
grant usage, select on sequence public.intensity_samples_id_seq to service_role;
grant usage, select on sequence public.body_measurements_id_seq to service_role;
grant usage, select on sequence public.menstrual_records_id_seq to service_role;
grant usage, select on sequence public.sleep_sessions_id_seq to service_role;
grant usage, select on sequence public.sleep_stages_id_seq to service_role;
grant usage, select on sequence public.workouts_id_seq to service_role;
grant usage, select on sequence public.glucose_samples_id_seq to service_role;
grant usage, select on sequence public.diet_meals_id_seq to service_role;
grant usage, select on sequence public.diet_food_items_id_seq to service_role;
grant usage, select on sequence public.device_presence_id_seq to service_role;


commit;
