create table if not exists public.glucose_samples (
    id bigint generated by default as identity primary key,
    source text not null,
    source_record_id text not null,
    measured_at timestamptz not null,
    glucose_mg_dl integer not null check (glucose_mg_dl > 0),
    glucose_mmol_l numeric(6,2) not null check (glucose_mmol_l > 0),
    direction text,
    created_at timestamptz not null default now(),
    unique (source, source_record_id)
);

create index if not exists glucose_samples_source_measured_at_idx
    on public.glucose_samples (source, measured_at desc);

alter table public.glucose_samples enable row level security;
