create table if not exists public.device_presence (
    id bigint generated by default as identity primary key,
    observed_at timestamptz not null,
    device text not null default 'primary_phone',
    event text not null check (event = 'unlock'),
    latitude numeric(6, 3) not null check (latitude between -90 and 90),
    longitude numeric(7, 3) not null check (longitude between -180 and 180),
    accuracy numeric(10, 2) check (accuracy is null or accuracy >= 0),
    city text,
    region text,
    country text,
    source text not null default 'automate_location'
        check (source = 'automate_location'),
    created_at timestamptz not null default now()
);

create index if not exists device_presence_device_observed_idx
    on public.device_presence (device, observed_at desc);

create table if not exists public.wake_report_deliveries (
    id uuid primary key,
    report_date date not null,
    device text not null default 'primary_phone',
    sleep_source_record_id text not null,
    sleep_fingerprint text not null,
    report_kind text not null check (
        report_kind in ('morning', 'sleep_update', 'new_sleep')
    ),
    includes_yesterday_health boolean not null default false,
    sleep_snapshot jsonb not null,
    presence_id bigint references public.device_presence(id) on delete set null,
    status text not null check (status in ('triggering', 'completed')),
    claimed_at timestamptz not null,
    triggered_at timestamptz,
    created_at timestamptz not null default now(),
    unique (device, sleep_fingerprint)
);

create index if not exists wake_report_deliveries_day_idx
    on public.wake_report_deliveries (device, report_date, created_at);

create index if not exists wake_report_deliveries_presence_idx
    on public.wake_report_deliveries (presence_id);

alter table public.device_presence enable row level security;
alter table public.wake_report_deliveries enable row level security;

revoke all on table public.device_presence from anon, authenticated;
revoke all on table public.wake_report_deliveries from anon, authenticated;
revoke all on sequence public.device_presence_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.device_presence to service_role;
grant select, insert, update, delete on table public.wake_report_deliveries to service_role;
grant usage, select on sequence public.device_presence_id_seq to service_role;
