-- Normalized Xiaomi Health diet records.
-- The production database may already contain these tables from the initial
-- read-only probe migration; every statement is idempotent for that case.

create table if not exists public.diet_meals (
    id bigint generated by default as identity primary key,
    source text not null default 'xiaomi',
    source_meal_id text not null,
    meal_date date not null,
    dining smallint not null,
    meal_type text not null check (
        meal_type in (
            'breakfast',
            'morning_snack',
            'lunch',
            'afternoon_snack',
            'dinner',
            'evening_snack',
            'other'
        )
    ),
    recorded_at timestamptz,
    total_calorie_kcal numeric,
    total_protein_g numeric,
    total_carbohydrate_g numeric,
    total_fat_g numeric,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_meal_id)
);

create table if not exists public.diet_food_items (
    id bigint generated by default as identity primary key,
    diet_meal_id bigint not null references public.diet_meals(id) on delete cascade,
    source text not null default 'xiaomi',
    source_item_id text not null,
    item_index integer not null check (item_index >= 0),
    food_id text,
    name text,
    quantity numeric,
    unit text,
    calorie_kcal numeric,
    protein_g numeric,
    carbohydrate_g numeric,
    fat_g numeric,
    dietary_fiber_g numeric,
    minerals numeric,
    vitamins numeric,
    health_light smallint,
    image_url text,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_item_id, item_index)
);

create index if not exists diet_meals_recorded_at_idx
    on public.diet_meals (recorded_at);
create index if not exists diet_meals_meal_date_idx
    on public.diet_meals (meal_date);
create index if not exists diet_food_items_meal_idx
    on public.diet_food_items (diet_meal_id);

alter table public.diet_meals enable row level security;
alter table public.diet_food_items enable row level security;
